services:
  build:
    build: .
    command: make master.pdf
    working_dir: /main
    volumes:
      - './whitepaper:/main'
      - './output:/output'
  shell:
    image: build
    command: bash
    working_dir: /main
    volumes:
      - './whitepaper:/main'
      - './output:/output'
